# Generated by Django 4.2.3 on 2025-06-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apilog",
            name="status_code",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="apilog",
            name="success",
            field=models.BooleanField(default=True),
        ),
    ]
